
server:
  port: 8080

uploadFolder: D:/
file.upload.path: D://images/
file.upload.path.relative: /images/**

spring:
  elasticsearch:
    rest:
      uris: http://39.103.152.64:9200
      username: elastic
      password: 123456
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: 13941715477@163.com
    password: FYLGHIKOZQJWUYSV

  mvc:
    static-path-pattern: /**
  thymeleaf:
    cache: false
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: LEGACYHTML5
    suffix: .html
    prefix: classpath:/templates/
  resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    filters: stat
#    initialSize: 100
#    maxActive: 1000
#    maxOpenPreparedStatements: 20
#    maxWait: 60000
#    minEvictableIdleTimeMillis: 300000
#    minIdle: 500
#    poolPreparedStatements: true
#    testOnBorrow: false
#    testOnReturn: false
#    testWhileIdle: true
#    timeBetweenEvictionRunsMillis: 60000
#    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.103.152.64:3306/elastic_seckill?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 289989142
#    validationQuery: select 'x'

config:
#  jwt:
#    secret: lihengyu.top #这里可以自己定制
#    expire: 30 # 过期时间,单位分钟
#    header: lhyToken #随意定制

redis:
  # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
  database: 3
  # redis服务器地址（默认为loaclhost）
  host: loaclhost
  # redis端口（默认为6379）
  post: 6379
  # redis访问密码（默认为空）
  password:
  # redis连接超时时间（单位毫秒）
  timeout: 0
  # redis连接池配置
  pool:
    # 最大可用连接数（默认为8，负数表示无限）
    max-active: 8
    # 最大空闲连接数（默认为8，负数表示无限）
    max-idle: 8
    # 最小空闲连接数（默认为0，该值只有为正数才有用）
    min-idle: 0
    # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
    max-wait: -1

mybatis-plus:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql
  mapperLocations: classpath:com/lhy/seckill/mapper/*.xml
  type-aliases-package: com.lhy.seckill.mapper